import { test, expect } from '@playwright/test'
import { expectNoBrokenImages, screenshot, trackErrors } from './helpers'

test.describe('every screen loads cleanly', () => {
  test('home', async ({ page }) => {
    const errors = trackErrors(page)
    await page.goto('/')
    await expect(page.getByRole('heading', { level: 1 })).toContainText('Learn to mix')
    await expect(page.getByTestId('home-free-bar')).toBeVisible()
    await expect(page.getByTestId('home-recipes')).toBeVisible()
    await expect(page.getByTestId('home-challenge')).toBeVisible()
    await expectNoBrokenImages(page)
    await screenshot(page, '01-home')
    expect(errors).toEqual([])
  })

  test('free bar', async ({ page }) => {
    const errors = trackErrors(page)
    await page.goto('/bar')
    await expect(page.getByTestId('mode-label')).toHaveText('Free Bar')
    // All categories are present on the shelf tabs.
    for (const c of ['vodka', 'gin', 'rum', 'tequila', 'whiskey', 'liqueurs', 'vermouth-bitters', 'juices', 'sodas', 'syrups', 'garnishes']) {
      await expect(page.getByTestId(`shelf-tab-${c}`)).toBeVisible()
    }
    // Tools, glasses and stations.
    await expect(page.getByTestId('station-shaker')).toBeVisible()
    await expect(page.getByTestId('station-mixing')).toBeVisible()
    await expect(page.getByTestId('station-jigger')).toBeVisible()
    await expect(page.getByTestId('tool-spoon')).toBeVisible()
    await expect(page.getByTestId('tool-muddler')).toBeVisible()
    await expect(page.getByTestId('tool-strainer')).toBeVisible()
    await expect(page.getByTestId('ice-bucket')).toBeVisible()
    await expect(page.getByTestId('rim-station')).toBeVisible()
    await expect(page.getByTestId('bin')).toBeVisible()
    for (const g of ['highball', 'rocks', 'coupe', 'martini', 'margarita', 'shot', 'collins', 'hurricane']) {
      await expect(page.getByTestId(`rack-${g}`)).toBeVisible()
    }
    // Switching shelves shows distinct bottles.
    await page.getByTestId('shelf-tab-gin').click()
    await expect(page.getByTestId('bottle-gin')).toBeVisible()
    await expect(page.getByTestId('bottle-old-tom-gin')).toBeVisible()
    await page.getByTestId('shelf-tab-juices').click()
    await expect(page.getByTestId('bottle-lime-juice')).toBeVisible()
    await page.getByTestId('shelf-tab-vodka').click()
    await expectNoBrokenImages(page)
    await screenshot(page, '02-free-bar')
    expect(errors).toEqual([])
  })

  test('recipe library with search and filters', async ({ page }) => {
    const errors = trackErrors(page)
    await page.goto('/recipes')
    const cards = page.locator('[data-testid^="recipe-card-"]')
    expect(await cards.count()).toBeGreaterThanOrEqual(150)
    await page.getByTestId('recipe-search').fill('margarita')
    await expect(page.getByTestId('recipe-card-margarita')).toBeVisible()
    expect(await cards.count()).toBeLessThan(12)
    await page.getByTestId('recipe-search').fill('')
    await page.getByTestId('filter-base').selectOption('gin')
    await page.getByTestId('filter-method').selectOption('stir')
    await expect(page.getByTestId('recipe-card-dry-martini')).toBeVisible()
    await expect(page.getByTestId('recipe-card-margarita')).toHaveCount(0)
    await page.getByTestId('filter-base').selectOption('')
    await page.getByTestId('filter-method').selectOption('')
    await page.getByTestId('filter-difficulty').selectOption('hard')
    await expect(page.getByTestId('recipe-card-zombie')).toBeVisible()
    await page.getByTestId('filter-difficulty').selectOption('')
    await page.getByTestId('filter-glass').selectOption('hurricane')
    await expect(page.getByTestId('recipe-card-pina-colada')).toBeVisible()
    await page.getByTestId('filter-glass').selectOption('')
    await expectNoBrokenImages(page)
    await screenshot(page, '03-recipes')
    expect(errors).toEqual([])
  })

  test('recipe detail shows the finished drink and full spec', async ({ page }) => {
    const errors = trackErrors(page)
    await page.goto('/recipes/margarita')
    await expect(page.getByRole('heading', { level: 1 })).toHaveText('Margarita')
    await expect(page.getByTestId('recipe-image-margarita')).toBeVisible()
    await expect(page.getByTestId('spec-tequila')).toContainText('50 ml')
    await expect(page.getByTestId('spec-tequila')).toContainText('1.67 oz')
    await expect(page.getByTestId('recipe-spec')).toContainText('Salt')
    await expect(page.getByTestId('recipe-spec')).toContainText('Lime Wedge')
    await expect(page.getByTestId('btn-guided')).toBeVisible()
    await expectNoBrokenImages(page)
    await screenshot(page, '04-recipe-detail')
    expect(errors).toEqual([])
  })

  test('challenge picker and progress', async ({ page }) => {
    const errors = trackErrors(page)
    await page.goto('/challenge')
    await expect(page.getByTestId('challenge-easy')).toBeVisible()
    await expect(page.getByTestId('challenge-any')).toBeVisible()
    await screenshot(page, '05-challenge-picker')
    await page.goto('/progress')
    await expect(page.getByTestId('stat-mastered')).toContainText('0 /')
    await expect(page.getByTestId('progress-easy')).toBeVisible()
    await screenshot(page, '06-progress-empty')
    expect(errors).toEqual([])
  })

  test('mobile layout works with touch-sized viewport', async ({ browser }) => {
    const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true })
    const page = await ctx.newPage()
    const errors = trackErrors(page)
    await page.goto('/bar')
    await expect(page.getByTestId('mobile-bar')).toBeVisible()
    await expect(page.getByTestId('rack-highball')).toBeVisible()
    const width = await page.evaluate(() => document.documentElement.scrollWidth)
    expect(width).toBeLessThanOrEqual(390)
    await page.getByTestId('rack-highball').tap()
    await expect(page.getByTestId('counter-glass')).toHaveAttribute('data-glass', 'highball')
    await screenshot(page, '07-mobile-bar')
    expect(errors).toEqual([])
    await ctx.close()
  })
})
